### PR TITLE
fix issue with text file encoding gzip

### PR DESCRIPTION
**Pull request by RemyNoulin**
The issue is discussed at:
https://github.com/CollectionFS/Meteor-CollectionFS/issues/664

### CODE REVIEW

**Comment by aldeed** [comment]
@raix does this fix look correct to you? I haven't looked at this code recently and I don't think I fully understand the root issue. I'm sure it is a fix, but I don't want to cause issues for other types of downloads.

**Comment by raix** [comment]
my concern is that we could risk having a connection "hanging"?

**Comment by RemyNoulin** [comment]
I think the connection is finished already when res.end is called.
Node throws an error in _stream_writable_.js because the writable state
finished is true.

BR
Remy

**Comment by aldeed** [comment]
It is very difficult to know whether the logic is correct when just fixing for a single test case. I think most likely the correct fix will be something like this:

```js
      function sendResponseIfDone() {
          res.statusCode = self.statusCode;
        // If no streams are waiting
        if (self._streamsWaiting === 0 &&
            (self.statusCode === 200 || self.statusCode === 206) &&
            self.done &&
            !self._responseSent) {
          self._responseSent = true;
          res.end(resultBuffer);
        }
      }
```

That should stop it from trying to call `res.end` twice, but without gzip-specific check. @RemyNoulin can you try that fix? Otherwise we can check finished state, too.

**Comment by RemyNoulin** [comment]
It works fine with your change, I tested with text, mp3 and gif files.

**Comment by raix** [comment]
we should still make sure the stream is ended:
```js
if (!res.finished) {
} // else don't try
```

**Comment by aldeed** [comment]
I released this fix (including `res.finished` check) in 0.0.30. Please add `cfs:http-methods@0.0.30` to your app to ensure it's using this version and see if that fixes your issues.

**Pull request closed without merging**
