### PR TITLE
fix 206 range request

### PR DESCRIPTION
**Pull request by cherbst**
Second part of the fix to https://github.com/CollectionFS/Meteor-CollectionFS/issues/502

### CODE REVIEW

**Comment by cherbst** [comment]
I have updated the PR. The previous version was not playing well with request errors.

**Comment by aldeed** [comment]
@cherbst, cool looks good! Can you change it to merge into `devel` instead of `master`? We move to master once we release it.

**Comment by cherbst** [comment]
Do I miss something here? There is no branch ```devel```

**Comment by aldeed** [comment]
No, my bad. I thought this was the main CFS repo.

**Pull request merged**
